### ISSUE TITLE
Can't build on ghc 7.8

### ISSUE THREAD

**Issue by winterland1989** [s9gf4ult/type-fun#1]
I'd like to use this library but i need support at least ghc-7.8, currently build on ghc-7.8 result in errors like this:

``` bash
src/TypeFun/Data/Peano.hs:16:30:
    Can't make a derived instance of ‘Typeable N’:
      You need DeriveDataTypeable to derive an instance for this class
```

It can be easily fixed by enable `DeriveDataTypeable`.

If you're willing to add dependency on [type-compat](http://hackage.haskell.org/package/types-compat), then we can even get gcc-7.6 support, i'd like to make a pr and setup travis to monitor building. Is this plan ok to you?

**Comment by winterland1989** [comment]
The simplest solution to make it build on ghc-7.8  is adding `DeriveDataTypeable` to cable file, since this doesn't require release new version. Can you please update cabal information on hackage when you get time?

**Comment by s9gf4ult** [comment]
I have fixed `type-fun` to work with `ghc-7.8.4`, it is in master now. You can add travis support and try to make it work with `ghc-7.6` if you wish, but I am not sure it is posible. I am using `stack` and it does not support `ghc-7.6` so I can not check workability with old compillers. Also, supporting old compillers is not a primary feature for this experimental library and may be broken for some reasons.

**Comment by winterland1989** [comment]
thanks！please make a release ；）

**Comment by s9gf4ult** [comment]
http://hackage.haskell.org/package/type-fun-0.1.0
done.
